---
#tasks:
#  - name: ~/.vimrc
#    copy:
#      src: "files/.vimrc"
#      dest: "~/.vimrc"
#      mode: '0644'

#  - name: ~/.zshrc
#    copy:
#      src: "files/.zshrc"
#      dest: "~/.zshrc"
#      mode: '0644'
tasks:
  - name: source
    shell: source ~/.zshrc