---
- name: copy .vimrc file
  copy:
    src: "files/.vimrc"
    dest: "~/.vimrc"
    mode: '0644'

- name: copy .zshrc file
  copy:
    src: "files/.zshrc"
    dest: "~/.zshrc"
    mode: '0644'

- name: source
  shell: source ~/.zshrc