---
- name: ~/.vimrc
  copy:
    src: "files/.vimrc"
    dest: "~/.vimrc"
    mode: '0644'

- name: ~/.zshrc
  copy:
    src: "files/.zshrc"
    dest: "~/.zshrc"
    mode: '0644'

- name: source
  command: /bin/zsh "source ~/.zshrc"
  register: res
  changed_when: res.rc != 0
