---
taps:
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - homebrew/core

packages:
  - { name: zsh, state: present }
  - { name: git, state: present }
  - { name: wget, state: present }
  - { name: vim, state: present }
  - { name: tree, state: present }
  - { name: openssl, state: present }
  - { name: tmux, state: present }
  - { name: gh, state: present }
  - { name: awscli, state: present }
  - { name: jq, state: present }
  - { name: nkf, state: present }
  - { name: anyenv, state: present }
  - { name: readline, state: present }
  - { name: xz, state: present }
  - { name: zsh-completions, state: present }
  - { name: starship, state: present }
  - { name: nodebrew, state: present }
  - { name: tig, state: present }
