# This is a basic workflow to help you get started with Actions

name: ansible CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: "roles/*"
          override-deps: |
            ansible==2.10
            ansible-lint==4.2.0
          args: ""
